# Generated by Django 4.2.7 on 2025-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='demirbaş adı')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='seri numarası')),
                ('status', models.CharField(choices=[('available', 'Müsait'), ('assigned', 'Atanmış'), ('broken', 'Arızalı'), ('maintenance', 'Bakımda'), ('retired', 'Emekli')], default='available', max_length=20, verbose_name='durum')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='satın alma tarihi')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='garanti bitiş tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'demirbaş',
                'verbose_name_plural': 'demirbaşlar',
                'ordering': ['name'],
            },
        ),
    ]
