# Generated by Django 4.2.7 on 2025-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kategori adı')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategoriler',
                'ordering': ['name'],
            },
        ),
    ]
