# Generated by Django 4.2.7 on 2025-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='atanma tarihi')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='iade tarihi')),
                ('condition_on_return', models.TextField(blank=True, verbose_name='iade durumu')),
            ],
            options={
                'verbose_name': 'atama',
                'verbose_name_plural': 'atamalar',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
